config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'user/login_form'

  post 'user/login'

  get 'user/logout'

  get 'user/new'

  post 'user/create'
  
  get 'user/verify'
  
  get 'user/forgot_form'
  
  post 'user/forgot'
  
  get 'user/forgot_change'
  
  post 'user/forgot_confirm'
  

  get 'comment/new'

  get 'comment/create'

  get 'comment/delete'

  get 'post/create'

  get 'post/new'
  
  get 'post/modify'
  
  get 'post/update'
  
  get 'post/delete'
  
  root 'post#list'
  
  get 'user/profile'
  post 'user/profile'

end

app/models/post.rb
class Post < ActiveRecord::Base
    resourcify
    include Authority::Abilities
    
    has_many :comments
    belongs_to :user
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  
  # skip_before_filter :require_login, :only => [:list]
  before_action :authenticate_user!, except: [ :list ]
  
  def create
    _author = params[:author]
    _title = params[:title]
    _contents = params[:contents]
    
    _lat = params[:lat]
    _lng = params[:lng]
    _address = params[:address]
    
    post = Post.new(author: _author, title: _title, contents: _contents) ## record / row
    post.user = current_user
    post.lat = _lat
    post.lng = _lng 
    post.address = _address
    post.save
    
    redirect_to controller:'post', action:'list'
  end

  def new
    
  end
  
  def list
    ## fix 19
    @posts = Post.all.paginate(page: params[:page], per_page: 5)
    
  end
  
  def modify
     
    _id = params[:id]
    @post = Post.find(_id)
    authorize_action_for @post
    
  end
  
  def update 
     
    _id = params[:id]
    _author = params[:author]
    _title = params[:title]
    _contents = params[:contents]
    
    @post = Post.find(_id)
    authorize_action_for @post
    
    @post.author = _author
    @post.title = _title
    @post.contents = _contents
    
    @post.save
    
    redirect_to controller: 'post', action: 'list'
  end
  
  def delete
     
    _id = params[:id]
    
    @post = Post.find(_id)
    authorize_action_for @post
    @post.destroy
    
    redirect_to controller: 'post', action: 'list'
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/list.html.erb
<h3>방명록 리스트</h3>
<a href="/post/new" style="float:right;display:inline-block;">
    <button>새 글</button>
</a>

	<% if user_signed_in? %>
	  <p>현재 로그인된 유저의 이메일 : <%= current_user.email %></p>
	  <!-- add 17 -->
	  <img src="<%= current_user.profile %>" class="img img-thumbnail" style="width:100px;height:100px;object-fit: cover;">
	  <p><%= link_to "프로필", :controller => "user", :action => "profile" %> </p>
	  <!-- end 17 -->
	  <p><%= link_to "로그아웃", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?" } %></p>
	<% else %>
	  <p><%= link_to "로그인", new_user_session_path %></p>
	<% end %>
	
	
<div id="map" style="width:100%;height:400px;"></div>
<ul>
    <% @posts.each do |post| %>
    <li>
        <h4><%=post.id%>, <%=post.title%></h4>
        
    		<% if user_signed_in? %>
    		  <%= link_to '수정', post_modify_path(post) if post.updatable_by? current_user %>&nbsp;
    		  <%= link_to '삭제', post_delete_path(post), data: { confirm: 'Are you sure?' } if post.deletable_by? current_user %>
    		<% end %>
            <!--<a href="/post/modify?id=<%=post.id%>">수정</a>-->
            <!--<a href="/post/delete?id=<%=post.id%>">삭제</a>-->
            <a href="/comment/new?id=<%=post.id%>">댓글</a>
        <hr>
        <%=post.contents%>
        <hr>
        <%=post.author%>, <%=post.created_at.in_time_zone(9).to_formatted_s(:short)  %>
        
        <hr>
        <ol>
        <% post.comments.each do |comment| %>
            <li><%=comment.contents%>, <a href="/comment/delete?id=<%=comment.id%>">X</a></li>
        <% end %>
        </ol>
    </li>
    <% end %>
</ul>

<%= will_paginate @posts, :previous_label => t("이전"), :next_label => t("다음") %>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={다음지도key}"></script>
<script>
	var container = document.getElementById('map');
	var options = {
		center: new daum.maps.LatLng(37.5241937,126.9821703),
		level: 3
	};

	var map = new daum.maps.Map(container, options);
	
	// 마커를 표시할 위치와 내용을 가지고 있는 객체 배열입니다 
	var positions = [
    <% @posts.each do |post| %>
    	<% if post.lng != nil and post.lat != nil %>
	    {
	        content: '<div style="padding:5px;width:200px; text-align:center;"><%=post.address%></div>', 
	        latlng: new daum.maps.LatLng(<%=post.lat%>, <%=post.lng%>)
	    },
	    <% end %>
	<% end %>
	];
	
	
	for (var i = 0; i < positions.length; i ++) {
	    // 마커를 생성합니다
	    var marker = new daum.maps.Marker({
	        map: map, // 마커를 표시할 지도
	        position: positions[i].latlng // 마커의 위치
	    });
	
	    // 마커에 표시할 인포윈도우를 생성합니다 
	    var infowindow = new daum.maps.InfoWindow({
	        content: positions[i].content // 인포윈도우에 표시할 내용
	    });
	
	    // 마커에 이벤트를 등록하는 함수 만들고 즉시 호출하여 클로저를 만듭니다
	    // 클로저를 만들어 주지 않으면 마지막 마커에만 이벤트가 등록됩니다
	    (function(marker, infowindow) {
	        // 마커에 mouseover 이벤트를 등록하고 마우스 오버 시 인포윈도우를 표시합니다 
	        daum.maps.event.addListener(marker, 'mouseover', function() {
	            infowindow.open(map, marker);
	        });
	
	        // 마커에 mouseout 이벤트를 등록하고 마우스 아웃 시 인포윈도우를 닫습니다
	        daum.maps.event.addListener(marker, 'mouseout', function() {
	            infowindow.close();
	        });
	    })(marker, infowindow);
	}
	
</script>

app/views/post/modify.html.erb
<h1>글 수정하기</h1>
<form action="/post/update">
    <input type="hidden" name="id" value="<%=@post.id%>">
    <p>
        <label for="title">제목</label>
        <input type="text" name="title" value="<%=@post.title%>">
    </p>
    
    <p>
        <label for="author">작성자</label>
        <input type="text" name="author" value="<%=@post.author%>">
    </p>
    <hr>
    <textarea name="contents"><%=@post.contents%></textarea>
    <button type="submit">수정하기!</button>
</form>

app/views/post/new.html.erb
<h1>Post#new</h1>
<form action="/post/create">
    
    
    <p>
        <label for="title">제목</label>
        <input type="text" name="title">
    </p>
    
    <p>
        <label for="author">작성자</label>
        <input type="text" name="author">
    </p>
    
    <p>
        <input type="hidden" id="lat" name="lat" value="0">
        <input type="hidden" id="lng" name="lng" value="0">
        <input type="hidden" id="address" name="address" value="">
        <div id="map" style="width:500px;height:400px;"></div>
        <div id="map_message"></div>
    </p>
    
    <hr>
    <textarea name="contents"></textarea>
    
    
    <button type="submit">글쓰기!</button>
</form>

<!-- services 라이브러리 불러오기 -->
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey={다음지도key}&libraries=services"></script>
<script defer>
	var container = document.getElementById('map');
	var options = {
		center: new daum.maps.LatLng(37.5241937,126.9821703),
		level: 3
	};

	var map = new daum.maps.Map(container, options);
	// 주소-좌표 변환 객체를 생성합니다
	var geocoder = new daum.maps.services.Geocoder();
	var marker = null;
	
	// 지도에 클릭 이벤트를 등록합니다
    // 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다
    daum.maps.event.addListener(map, 'click', function(mouseEvent) {      
        if (marker == null) {
            marker = new daum.maps.Marker({ 
    		    // 지도 중심좌표에 마커를 생성합니다 
    		    position: map.getCenter() 
    		}); 
    		// 지도에 마커를 표시합니다
    		marker.setMap(map);
        }
        
        
        // 클릭한 위도, 경도 정보를 가져옵니다 
        var latlng = mouseEvent.latLng; 
        
        // 마커 위치를 클릭한 위치로 옮깁니다
        marker.setPosition(latlng);
        
        
        // 데이터 히든 필드에 지정
        $('#lat').val(latlng.getLat());
        $('#lng').val(latlng.getLng());
        
        // 지오로케이션
        geocoder.coord2Address(latlng.getLng(), latlng.getLat(), function(result, status) {
            // 안내 메세지 표시
            var address_name = ''
    		if (result.length > 0) {
    			address_name = result[0].address.address_name;
    		}
            $('#map_message').text('선택한 위치는 '+address_name+' ('+latlng.getLat()+', '+latlng.getLng()+')입니다.');
            
            // 주소 지정
            $('#address').val(address_name);
    	});
        
    });
</script>